### ISSUE TITLE
every update

### ISSUE THREAD

**Issue by progamer562** [tronikos/default_config_disabler#3]
once ha updates the integration brakes and have to restart every time for this to work

**Comment by whc2001** [comment]
Same here. Enabled and added some logging, seems like the `async_setup_entry` get called normally after updating and got executed to the `SERVICE_HOMEASSISTANT_RESTART`, but for some reason it does not restart HA successfully. 

![image](https://github.com/tronikos/default_config_disabler/assets/16266909/3e1a3f35-b679-49e8-97af-4a38f5581da4)

**Comment by codyc1515** [comment]
It appears this integration works by grabbing the HA Core `default_config` integration's `manifest.json` file and manipulating that same file directly. It should go without saying that this is quite risky and could break your entire HA from booting.

It makes sense then that when you update HA Core that the file would be overwritten (because the docker image would be updated and thus the HA Core integrations). You would need to reboot one more time following an update to disable those integrations in that case.

The only alternative would be to DIY your own docker image which, while possible, I would not recommend.

**Comment by whc2001** [comment]
This is currently how I solved it in a brute force way: The problem is the integration is unable to restart HA correctly and don't have a way to detect whether it restarted successfully or not. Keep on trying to reboot should make it work.

```python
# ...
import asyncio
# ...

        # ...
        _LOGGER.warning("Restarting Home Assistant to use the updated default_config")
        await hass.services.async_call(HA_DOMAIN, SERVICE_HOMEASSISTANT_RESTART)

######## ADDED CODE STARTS HERE ########
    async def on_started(event):
        still_alive_components = []
        all_alive_components = hass.data["components"].keys()
        for disabled_component in disabled_components:
            if disabled_component in all_alive_components:
                still_alive_components.append(disabled_component)
        if len(still_alive_components) > 0:
            _LOGGER.error("Components: %s still alive, request restart", still_alive_components)
            while True:
                await hass.services.async_call(HA_DOMAIN, SERVICE_HOMEASSISTANT_RESTART)
                await asyncio.sleep(1)
    hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STARTED, on_started)
######## ADDED CODE ENDS HERE ########

    entry.async_on_unload(entry.add_update_listener(update_listener))
    # ...
```

It basically listens the `EVENT_HOMEASSISTANT_STARTED`, and judge if there is any blacklisted integration still active. If so, going into an infinite loop trying to restart HA until the operation succeed.

I have tried this on `2024.2.0` and it works. After update the `cloud` integration which I have disabled appeared for a few seconds, then the entire thing is restarted and it disappeared. 

***Note that this is the perfect recipe for a potential bootloop. Use at your own risk.***

**Comment by tronikos** [comment]
Does the following work?
```python
        _LOGGER.warning("Restarting Home Assistant to use the updated default_config")
        # await hass.services.async_call(HA_DOMAIN, SERVICE_HOMEASSISTANT_RESTART)
        async def on_started(event):
            await hass.services.async_call(HA_DOMAIN, SERVICE_HOMEASSISTANT_RESTART)
        hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STARTED, on_started)
```

**Comment by whc2001** [comment]
> Does the following work?
> ```python
>         _LOGGER.warning("Restarting Home Assistant to use the updated default_config")
>         # await hass.services.async_call(HA_DOMAIN, SERVICE_HOMEASSISTANT_RESTART)
>         async def on_started(event):
>             await hass.services.async_call(HA_DOMAIN, SERVICE_HOMEASSISTANT_RESTART)
>         hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STARTED, on_started)
> ```

That seems promising, I'll rollback the update and try later today

**Comment by whc2001** [comment]
> Does the following work?
> 
> ```python
>         _LOGGER.warning("Restarting Home Assistant to use the updated default_config")
>         # await hass.services.async_call(HA_DOMAIN, SERVICE_HOMEASSISTANT_RESTART)
>         async def on_started(event):
>             await hass.services.async_call(HA_DOMAIN, SERVICE_HOMEASSISTANT_RESTART)
>         hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STARTED, on_started)
> ```

Unfortunately this does not work. The restart call is still not effective and is supressed silently.
